### ISSUE TITLE
Error with trailing unclosed comments

### ISSUE THREAD

**Issue by josephscott** [tubalmartin/YUI-CSS-compressor-PHP-port#23]
I ran into a problem with CSSmin hanging during the minification process.  Eventually I tracked it down to a problem with an unclosed comment at the end of the file.  It can be reproduced with this CSS:

``` css
/* Comment 1 */
/* Comment 2
```

When I run CSSmin against this it does the infinite loop thing until hitting the max execution time limit in PHP.

Yes the error is that user didn't close the comment, but I think a defensive approach would be to strip the unclosed trailing comment out.

**Comment by josephscott** [comment]
I'm experimenting with this approach:

```diff
diff --git a/cssmin.php b/cssmin.php
index fab0102..ac01811 100644
--- a/cssmin.php
+++ b/cssmin.php
@@ -75,9 +75,22 @@ class CSSmin
 
         $css = $this->extract_data_urls($css);
 
+        // Clean up trailing unclosed comments
+        $last_newline = strrpos( rtrim( $css ), "\n" );
+        if ( $last_newline !== false ) {
+            $last_comment_start = strrpos( $css, '/*', $last_newline );
+            if ( $last_comment_start !== false ) {
+                $last_comment_end = strrpos( $css, '*/', $last_comment_start );
+                if ( $last_comment_end === false ) {
+                    $css = substr( $css, 0, $last_newline );
+                }
+            }
+        }
+
         // collect all comment blocks...
         while (($start_index = $this->index_of($css, '/*', $start_index)) >= 0)
             $end_index = $this->index_of($css, '*/', $start_index + 2);
+
             if ($end_index < 0) {
                 $end_index = $length;
             }
@@ -774,4 +787,4 @@ class CSSmin
 
         return (int) $size;
     }
-}
\ No newline at end of file
+}
```

`tests/mine/unclosed-comment.css`

```css
a {
    color: blue;
}
html >/**/ body p {
    color: blue;
    /*a comment right before the IE star hack*/*width:auto;
    height:2%;
}

/* Comment 1 */

/* Comment 2
```

`tests/mine/unclosed-comment.css.min`

```css
a{color:blue}html>/**/body p{color:blue;*width:auto;height:2%}
```
