### ISSUE TITLE
Suggestion: remove one space before :not

### ISSUE THREAD

**Issue by rinart73** [tubalmartin/YUI-CSS-compressor-PHP-port#64]
Since Java version has the same output, it's not a bug. Just a suggestion for improvement.
Input:
```css
section  a   :not( .one  , .two  , [ data-x = " ab  c " ] ) {
  color  : red ;
}
```
Ouput:
```css
section a :not(.one,.two,[data-x=" ab  c "]){color:red}
```
Space before `:not` can be safely removed.
